supabase:
  url_swift:
    host: ${URL_SWIFT_HOST}
    api_key: ${URL_SWIFT_API_KEY}
    authority:
      schema: ${URL_SWIFT_SCHEMA}
      email: ${URL_SWIFT_EMAIL}
      password: ${URL_SWIFT_PWD}


  base62_key_generator:
    host: ${B62KG_HOST}
    api_key: ${B62KG_API_KEY}
    authority:
      schema: ${B62KG_SCHEMA}
      email: ${B62KG_EMAIL}
      password: ${B62KG_PWD}

quarkus:
  swagger-ui:
    always-include: true
    path: /swagger
  smallrye-openapi:
    info-title: URL Swift
    info-description: URL Swift is a service that allows you to shorten URLs.
    info-version: 1.0.0
    info-contact-name: Luca Corallo
    info-contact-email: corallo.luca@outlook.com
    info-contact-url: https://github.com/event-io/url-swift   
    store-schema-directory: target/

  jacoco:
   title: "URL Swift Coverage Analysis"
   footer: "Author: Luca Corallo"
  arc:
    dev-mode:
      monitoring-enabled: true
    test:
      disable-application-lifecycle-observers: true
  log:
    category:
      "org.jboss.resteasy.reactive.client.logging":
        level: DEBUG
  rest-client:
    logging:
      scope: request-response
      body-limit: 10000
    url_swift:
      url: ${URL_SWIFT_HOST}
      verify-host: true
    base62_key_generator:
      url: ${B62KG_HOST}
      verify-host: true
    supabase_auth:
      url: _ #Insert only for test purpose. In dev and prod the value is set dynamically.

"%dev":
  quarkus:
    rest-client:
      supabase_auth.scope: jakarta.inject.Singleton
      url_swift.scope: jakarta.inject.Singleton
      base62_key_generator.scope: jakarta.inject.Singleton

"%test":
  quarkus:
    rest-client:
      supabase_auth.scope: jakarta.enterprise.context.ApplicationScoped
      url_swift.scope: jakarta.enterprise.context.ApplicationScoped
      base62_key_generator.scope: jakarta.enterprise.context.ApplicationScoped