name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./
    shell: bash
  
jobs:
  unit_test:
    name: 'Run Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'JDK'

      - name: Set up Maven 3.9.4
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4
      
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean package
      
      - name: Run Unit Tests
        run: mvn test -Dtest="UrlSwiftServiceTest" -DfailIfNoTests=false

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}